apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator-demo
  template:
    metadata:
      labels:
        name: operator-demo
    spec:
      serviceAccountName: operator-demo
      containers:
        - name: operator-demo
          # Replace this with the built image name
          image: liuhaogui/operator-demo:v0.0.1
          command:
          - operator-demo
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operator-demo"
